// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmlpJ_MCJI5Q63cEqFeluY3dKpLIFxsQ',
    appId: '1:426337932545:web:2691d4f17208170f2ab700',
    messagingSenderId: '426337932545',
    projectId: 'gecw-stay',
    authDomain: 'gecw-stay.firebaseapp.com',
    storageBucket: 'gecw-stay.firebasestorage.app',
    measurementId: 'G-KX2QXY9T9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--Chu8THyGNkDGP_-PFUHZXPj54iScT0',
    appId: '1:426337932545:android:ed3b15b349dd2e752ab700',
    messagingSenderId: '426337932545',
    projectId: 'gecw-stay',
    storageBucket: 'gecw-stay.firebasestorage.app',
  );
}
